[package]
name = "unios-rs"
version = "0.0.1"
edition = 2025

[lib]
name = "build"
crate-type = ["staticlib"] # Links with C and C++

[dependencies]
libc = { workspace = true }

[build-dependencies]
cc = { workspace = true }

